connect-webapp/src/main/java/org/sklsft/connect/mvc/controller/CommonController.java
package org.sklsft.connect.mvc.controller;



import java.util.Date;

import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServletResponse;

import org.sklsft.commons.api.exception.ApplicationException;
import org.sklsft.commons.api.exception.TechnicalError;
import org.sklsft.connect.api.model.resources.of.AttachmentForm;
import org.sklsft.connect.api.model.resources.ov.AttachmentView;
import org.sklsft.connect.client.file.FileService;
import org.sklsft.social.util.text.DurationUtils;
import org.springframework.stereotype.Controller;

@Controller
public  class CommonController extends BaseController {
	
	@Inject
	private FileService fileService;
		
		
	
	public String getRestUrl(){
		return getJndiVar("restServerUrl");
	}
	
	
	public String getTimeMillis() {
		return String.valueOf(new Date().getTime());
	}
	
	
	public String getDuration(Date date) {
		return DurationUtils.getDuration(date);
	}
	
	
	public String openFile(AttachmentView attachment) {

		ServletOutputStream servletOutputStream = null;

		try {

			byte[] data = fileService.getFileContent(attachment.getRelativeUrl());

			HttpServletResponse response = (HttpServletResponse) FacesContext
					.getCurrentInstance().getExternalContext().getResponse();
			response.setContentType("application/octet-stream");

			response.setHeader(
					"Content-Disposition",
					"attachment;filename=" + attachment.getAttachmentName());

			servletOutputStream = response.getOutputStream();

			for (byte b : data) {
				servletOutputStream.write(b);
			}

			servletOutputStream.flush();
			servletOutputStream.close();

			response.flushBuffer();
			FacesContext.getCurrentInstance().responseComplete();

			return null;

		} catch (ApplicationException e) {
			displayError(e.getMessage());
			return null;
		} catch (Exception e) {
			displayError(TechnicalError.ERROR_UNKNOWN);
			return null;
		} finally {
			try {
				if (servletOutputStream != null) {
					servletOutputStream.close();
				}
			} catch (Exception e) {

			}
		}
	}
	
	
	public String openFile(AttachmentForm attachment) {

		ServletOutputStream servletOutputStream = null;

		try {

			byte[] data = attachment.getData();

			HttpServletResponse response = (HttpServletResponse) FacesContext
					.getCurrentInstance().getExternalContext().getResponse();
			response.setContentType("application/octet-stream");

			response.setHeader(
					"Content-Disposition",
					"attachment;filename=" + attachment.getAttachmentName());

			servletOutputStream = response.getOutputStream();

			for (byte b : data) {
				servletOutputStream.write(b);
			}

			servletOutputStream.flush();
			servletOutputStream.close();

			response.flushBuffer();
			FacesContext.getCurrentInstance().responseComplete();

			return null;

		} catch (ApplicationException e) {
			displayError(e.getMessage());
			return null;
		} catch (Exception e) {
			displayError(TechnicalError.ERROR_UNKNOWN);
			return null;
		} finally {
			try {
				if (servletOutputStream != null) {
					servletOutputStream.close();
				}
			} catch (Exception e) {

			}
		}
	}	
}

connect-webapp/src/main/webapp/templates/header-error.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

	

</ui:composition>

connect-webapp/src/main/webapp/templates/header-private-faculty.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html" xmlns:p="http://primefaces.org/ui">

	<h:form>
		<ul class="nav navbar-nav navbar-right pull-right">

			<li class="dropdown">
				<h:graphicImage value="#{commonController.getRestUrl()}#{indexView.account.relativeUrl}?time=#{commonController.timeMillis}"
					styleClass="navbar-profile" />
			</li>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					<h:outputText value="#{indexView.account.firstName}	#{indexView.account.lastName}" />
					
				</a>

				<div class="dropdown-menu dropdown-menu-right main">

					<div class="panel panel-popover">

						<div class="panel-body">


							<ul class="list-unstyled">
								<li>
									<p:link value="#{i18n.filloutCV}" outcome="/private/account/account-detail" icon="menu-not-selected" />
								</li>

								<li class="divider"></li>
								<li>
									<p:commandLink value="#{i18n.logout}" action="#{authenticationController.logout}" ajax="true" />
								</li>
							</ul>
						</div>
					</div>
				</div>
			</li>
		</ul>


	</h:form>

</ui:composition>

connect-webapp/src/main/webapp/templates/header-private.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html" xmlns:p="http://primefaces.org/ui">

	<h:form>
		<ul class="nav navbar-nav navbar-right pull-right">

			<li class="dropdown">
				<h:graphicImage value="#{commonController.getRestUrl()}#{indexView.account.relativeUrl}?time=#{commonController.timeMillis}"
					styleClass="navbar-profile" />
			</li>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					<h:outputText value="#{indexView.account.firstName}	#{indexView.account.lastName}" />
					
				</a>

				<div class="dropdown-menu dropdown-menu-right main">

					<div class="panel panel-popover">

						<div class="panel-body">


							<ul class="list-unstyled">

								<li>
									<p:link value="#{i18n.facultyIdentity}" outcome="/private/faculty/account-faculty-identity" icon="menu-not-selected" />
								</li>
								<li>
									<p:link value="#{i18n.facultyIntellectualContributions}" outcome="/private/faculty/account-faculty-IC" icon="menu-not-selected" />
								</li>
								<li>
									<p:link value="#{i18n.facultyEducationalBackground}" outcome="/private/faculty/account-faculty-EB" icon="menu-not-selected" />
								</li>
								<li>
									<p:link value="#{i18n.facultyWorkExperience}" outcome="/private/faculty/account-faculty-WE" icon="menu-not-selected" />
								</li>
								<li>
									<p:link value="#{i18n.facultyIUMActivities}" outcome="/private/faculty/account-faculty-IUMA" icon="menu-not-selected" />
								</li>
								<li>
									<p:link value="#{i18n.facultyAdministrativeDuties}" outcome="/private/faculty/account-faculty-AD" icon="menu-not-selected" />
								</li>								<li>
									<p:link value="#{i18n.accountParameters}" outcome="/private/account/account-detail" icon="menu-not-selected" />
								</li>

								<li class="divider"></li>
								<li>
									<p:commandLink value="#{i18n.logout}" action="#{authenticationController.logout}" ajax="true" />
								</li>
							</ul>
						</div>
					</div>
				</div>
			</li>
		</ul>


	</h:form>

</ui:composition>

connect-webapp/src/main/webapp/templates/header-public.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

	<h:form>

		<ul class="nav navbar-nav navbar-right pull-right">
			<li><p:commandLink
					oncomplete="$('#connectionModal').modal('show')"
					update=":connectionPanelGroup" value="#{i18n.connection}" /></li>
		</ul>
	</h:form>



</ui:composition>

connect-webapp/src/main/webapp/templates/template-error.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>${i18n.applicationName}</title>

	<meta name="viewport" content="width=device-width, initial-scale=1" />

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	
	<meta http-equiv="content-language" content="fr"/>

	<meta name="description" content="${i18n.description}" />

	<meta name="title" content="${i18n.title}" />

	<meta name="keywords" content="${i18n.keywords}" />

	<h:outputScript library="primefaces" name="jquery/jquery.js" />

	<h:outputScript library="js" name="bootstrap.min.js" />

	<h:outputStylesheet library="css" name="bootstrap.min.css" />

	<h:outputStylesheet library="css" name="styles.css" />

</h:head>

<h:body>

	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed"
					data-toggle="collapse" data-target="#navbar-menu">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" title="#{i18n.title}"
					href="#{application.contextPath}/private/index.xhtml">
					<h:graphicImage
						alt="#{i18n.title}" value="/resources/images/header/logo.png"
						height="50"/>
					#{i18n.applicationName}
				</a>
			</div>
			<div class="collapse navbar-collapse" id="navbar-menu">
				<ui:include src="/templates/header-error.xhtml" />
			</div>
		</div>
	</nav>
	
	<p:growl id="messages" sticky="false" life="4000" globalOnly="true" />

	<div class="container">		

		<ui:insert name="content" />

	</div>

</h:body>
</html>

connect-webapp/src/main/webapp/templates/template-private-faculty.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html" xmlns:p="http://primefaces.org/ui"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions">


<h:head>
	<title>#{i18n.applicationName}</title>

	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="content-language" content="fr" />
	<meta name="description" content="${i18n.description}" />
	<meta name="title" content="${i18n.title}" />
	
	<link rel="stylesheet" type="text/css" href="#{application.contextPath}/resources/css/bootstrap.min.css" />
	<link rel="stylesheet" type="text/css" href="#{application.contextPath}/resources/css/styles.css" />

</h:head>


<h:body>

	<script>
		window.onblur = function() {
			window.onfocus = function() {
				checkSecurityContext()
			}
		};
	</script>

	<h:form>
		<p:remoteCommand name="checkSecurityContext" action="#{securityController.checkContextChange()}" />

		<h:inputHidden value="#{indexView.token}" />
	</h:form>


	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container-fluid">
			<div class="navbar-header">
					<h:graphicImage alt="#{i18n.title}" value="/resources/images/header/logo.png" height="50" />
					#{i18n.applicationName}
			</div>
			<div class="nav" id="navbar-menu">
				<h:panelGroup id="headerPanelGroup">
					<ui:include src="/templates/header-private.xhtml" />
				</h:panelGroup>
			</div>
		</div>
	</nav>

	<p:growl id="messages" sticky="false" life="4000" globalOnly="true" />

	<div class="container">

		<ui:insert name="content" />

	</div>



	<div class="modal modal-default" id="organizationModal" tabindex="-1" aria-hidden="true">
		<div class="modal-dialog modal-lg">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">
						<span aria-hidden="true">x</span>
					</button>
					<h3 class="modal-title">#{i18n.filloutCV}</h3>
				</div>
				<div class="modal-body">

					<div class="form-group">
						<div class="row">
							<div class="col-sm-12">

								<h:panelGroup id="organizationPanelGroup">

									<ui:param name="view" value="#{organizationCreationView}" />

									<ui:param name="organization" value="#{organizationCreationView.organizationForm}" />

									<h:form class="form-vertical" id="organization-form">
										<div class="form-group">
											<p:outputLabel value="#{i18n.organizationName} : " />
											<p:inputText id="organizationName" styleClass="form-control" value="#{organization.name}" />
											<p:message for="organizationName" />
										</div>
										<div class="form-group">
											<p:outputLabel value="#{i18n.organizationDescription} : " />
											<p:inputTextarea id="organizationDescription" rows="3" styleClass="form-control" autoResize="true"
												value="#{organization.description}" />
											<p:message for="organizationDescription" />
										</div>

										<p:commandButton styleClass="btn btn-primary" action="#{organizationCreationController.createOrganization}"
											value="#{i18n.save}" ajax="true" update=":organizationPanelGroup, :messages" />
									</h:form>

								</h:panelGroup>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</h:body>

<h:outputScript library="primefaces" name="jquery/jquery.js" />
<h:outputScript library="js" name="bootstrap.min.js" />

</html>

connect-webapp/src/main/webapp/templates/template-private.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html" xmlns:p="http://primefaces.org/ui"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions">


<h:head>
	<title>#{i18n.applicationName}</title>

	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="content-language" content="fr" />
	<meta name="description" content="${i18n.description}" />
	<meta name="title" content="${i18n.title}" />
	
	<link rel="stylesheet" type="text/css" href="#{application.contextPath}/resources/css/bootstrap.min.css" />
	<link rel="stylesheet" type="text/css" href="#{application.contextPath}/resources/css/styles.css" />

</h:head>


<h:body>

	<script>
		window.onblur = function() {
			window.onfocus = function() {
				checkSecurityContext()
			}
		};
	</script>

	<h:form>
		<p:remoteCommand name="checkSecurityContext" action="#{securityController.checkContextChange()}" />

		<h:inputHidden value="#{indexView.token}" />
	</h:form>


	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container-fluid">
			<div class="navbar-header">
					<h:graphicImage alt="#{i18n.title}" value="/resources/images/header/logo.png" height="50" />
					#{i18n.applicationName}
			</div>
			<div class="nav" id="navbar-menu">
				<h:panelGroup id="headerPanelGroup">
					<ui:include src="/templates/header-private.xhtml" />
				</h:panelGroup>
			</div>
		</div>
	</nav>

	<p:growl id="messages" sticky="false" life="4000" globalOnly="true" />

	<div class="container">

		<ui:insert name="content" />

	</div>



	<div class="modal modal-default" id="organizationModal" tabindex="-1" aria-hidden="true">
		<div class="modal-dialog modal-lg">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">
						<span aria-hidden="true">x</span>
					</button>
					<h3 class="modal-title">#{i18n.addOrganization}</h3>
				</div>
				<div class="modal-body">

					<div class="form-group">
						<div class="row">
							<div class="col-sm-12">

								<h:panelGroup id="organizationPanelGroup">

									<ui:param name="view" value="#{organizationCreationView}" />

									<ui:param name="organization" value="#{organizationCreationView.organizationForm}" />

									<h:form class="form-vertical" id="organization-form">
										<div class="form-group">
											<p:outputLabel value="#{i18n.organizationName} : " />
											<p:inputText id="organizationName" styleClass="form-control" value="#{organization.name}" />
											<p:message for="organizationName" />
										</div>
										<div class="form-group">
											<p:outputLabel value="#{i18n.organizationDescription} : " />
											<p:inputTextarea id="organizationDescription" rows="3" styleClass="form-control" autoResize="true"
												value="#{organization.description}" />
											<p:message for="organizationDescription" />
										</div>

										<p:commandButton styleClass="btn btn-primary" action="#{organizationCreationController.createOrganization}"
											value="#{i18n.save}" ajax="true" update=":organizationPanelGroup, :messages" />
									</h:form>

								</h:panelGroup>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</h:body>

<h:outputScript library="primefaces" name="jquery/jquery.js" />
<h:outputScript library="js" name="bootstrap.min.js" />

</html>

connect-webapp/src/main/webapp/templates/template-public.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html" xmlns:p="http://primefaces.org/ui">


<h:head>
	<title>#{i18n.applicationName}</title>

	<meta name="viewport" content="width=device-width, initial-scale=1" />

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

	<meta http-equiv="content-language" content="fr" />

	<meta name="description" content="${i18n.description}" />

	<meta name="title" content="${i18n.title}" />

	<meta name="keywords" content="${i18n.keywords}" />

	<h:outputScript library="primefaces" name="jquery/jquery.js" />

	<h:outputScript library="js" name="bootstrap.min.js" />

	<h:outputStylesheet library="css" name="bootstrap.min.css" />

	<h:outputStylesheet library="css" name="styles.css" />

</h:head>

<h:body>

	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-menu">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
					<h:graphicImage title="#{i18n.title}" alt="#{i18n.title}" value="/resources/images/header/logo.png" height="50" />
					#{i18n.applicationName}
			</div>
			<div class="collapse navbar-collapse" id="navbar-menu">
				<ui:include src="/templates/header-public.xhtml" />
			</div>
		</div>
	</nav>

	<p:growl id="messages" sticky="false" life="4000" globalOnly="true" />

	<div class="container">

		<ui:insert name="content" />

	</div>


	<div class="modal modal-default" id="registerModal" tabindex="-1" aria-hidden="true">
		<div class="modal-dialog modal-md">
			<div class="modal-content">

				<h:panelGroup id="registerPanelGroup">

					<div class="modal-header">

						<button type="button" class="close" data-dismiss="modal">
							<span aria-hidden="true">X</span>
						</button>

						<h3>#{i18n.register}</h3>

					</div>

					<div class="modal-body">

						<h:form class="form-vertical">

							<ui:param name="form" value="#{accountCreationView.accountCreationForm}" />

							<ui:param name="account" value="#{form.personalData}" />

							<div class="form-group">
								<p:inputText id="firstName" value="#{account.firstName}" styleClass="form-control"
									placeholder="#{i18n.firstName}" />
								<p:message for="firstName" />
							</div>

							<div class="form-group">
								<p:inputText id="lastName" value="#{account.lastName}" styleClass="form-control" placeholder="#{i18n.lastName}" />
								<p:message for="lastName" />
							</div>

							<div class="form-group">
								<p:inputText id="email" value="#{form.email}" styleClass="form-control" placeholder="#{i18n.login}" />
								<p:message for="email" />
							</div>

							<div class="form-group">
								<p:password id="password" value="#{form.password}" styleClass="form-control" placeholder="#{i18n.password}" />
								<p:message for="password" />
							</div>

							<p:commandButton styleClass="btn btn-success" action="#{accountCreationController.createAccount}"
								update=":registerPanelGroup, :messages" value="#{i18n.save}">

							</p:commandButton>

						</h:form>

						<h:form class="form-vertical">
							<p:commandLink oncomplete="$('#registerModal').modal('hide');$('#connectionModal').modal('show')"
								value="#{i18n.alreadyRegistered}" />
						</h:form>
					</div>
				</h:panelGroup>
			</div>
		</div>
	</div>


	<div class="modal modal-default" id="connectionModal" tabindex="-1" aria-hidden="true">
		<div class="modal-dialog modal-sm">
			<div class="modal-content">

				<h:panelGroup id="connectionPanelGroup">

					<div class="modal-header">

						<button type="button" class="close" data-dismiss="modal">
							<span aria-hidden="true">X</span>
						</button>

						<h3>#{i18n.connection}</h3>

					</div>

					<div class="modal-body">

						<h:form class="form-vertical">

							<div class="form-group">
								<p:inputText id="login" value="#{authenticationView.loginForm.login}" placeholder="#{i18n.login}"
									styleClass="form-control">
								</p:inputText>
							</div>

							<div class="form-group">
								<p:password id="password" value="#{authenticationView.loginForm.password}" placeholder="#{i18n.password}"
									styleClass="form-control">
								</p:password>
							</div>

							<p:commandButton value="#{i18n.connection}" action="#{authenticationController.authenticate}"
								styleClass="btn btn-success" ajax="true" update=":messages">
							</p:commandButton>

						</h:form>

						<h:form class="form-vertical">
							<p:commandLink oncomplete="$('#connectionModal').modal('hide');$('#forgotPasswordModal').modal('show')"
								value="#{i18n.forgotPassword}" />
						</h:form>
					</div>
				</h:panelGroup>
			</div>
		</div>
	</div>


	<div class="modal modal-alpha" id="forgotPasswordModal" tabindex="-1" aria-hidden="true" data-backdrop="static">
		<div class="modal-dialog modal-md">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" onclick="$('#indexMainModal').show();">
						<span aria-hidden="true">X</span>
					</button>
					<h4 class="modal-title">#{i18n.forgotPassword}</h4>
				</div>
				<div class="modal-body">

					<h:form id="forgot-password-form" class="form-vertical">

						<div class="form-group">
							<p:inputText id="login" placeholder="#{i18n.login}" value="#{forgotPasswordView.emailForm.email}"
								styleClass="form-control" />
							<p:message for="login" />
						</div>

						<p:commandButton styleClass="btn btn-primary" value="#{i18n.resetPassword}"
							action="#{forgotPasswordController.sendResetPassword}" ajax="true" update="forgot-password-form, :messages"
							oncomplete="if(!args.validationFailed &amp;&amp; args.maximumSeverity.ordinal==0) $('#forgotPasswordModal').modal('hide');">
						</p:commandButton>

					</h:form>
				</div>
			</div>
		</div>
	</div>

</h:body>
</html>